//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirPort
    {
        public AirPort()
        {
            this.Airport_Route = new HashSet<Airport_Route>();
            this.Airport_Route1 = new HashSet<Airport_Route>();
            this.Planes = new HashSet<Plane>();
        }
    
        public string IATA { get; set; }
        public string AirportName { get; set; }
        public string AirportAddress { get; set; }
    
        public virtual ICollection<Airport_Route> Airport_Route { get; set; }
        public virtual ICollection<Airport_Route> Airport_Route1 { get; set; }
        public virtual ICollection<Plane> Planes { get; set; }
    }
}
