//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Planes = new HashSet<Plane>();
            this.Routes = new HashSet<Route>();
        }
    
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
    
        public virtual ICollection<Plane> Planes { get; set; }
        public virtual ICollection<Route> Routes { get; set; }
    }
}
