//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public Route()
        {
            this.Planes = new HashSet<Plane>();
            this.Airport_Route = new HashSet<Airport_Route>();
        }
    
        public int RouteId { get; set; }
        public Nullable<int> Company_CompanyId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<Plane> Planes { get; set; }
        public virtual ICollection<Airport_Route> Airport_Route { get; set; }
    }
}
